---
- hosts: all

  pre_tasks:
    - homebrew: name='{{ item }}' update_homebrew=yes state=present
      with_items:
        - bash-completion
        - git
        - tmux
        - pass
        - htop
        - reattach-to-user-namespace
        - bzr
        - hg
        - imagemagick
        - ctags
        - vim
        - node
        - android-sdk
        - mongodb
        - mysql
        - redis
        - direnv
        - rbenv
        - ruby-build
        - ssh-copy-id
        - wget
      tags: brew

    # - role: npm_package
    #   package_name: grunt
    #
    # - role: npm_package
    #   package_name: bower
    #

    - homebrew_cask: name='{{ item }}' state=present
      with_items:
        - font-source-code-pro
        # - font-source-code-powerline # no more?
        - alfred
        - spotify
        - google-chrome
        - firefox
        - java
        - postgres
        - virtualbox
        - slack
        - wavebox
        - harvest
        - transmission
        - android-file-transfer
        - disk-inventory-x
        - docker
        - the-unarchiver
        - calibre
        - jdownloader
        - cyberduck
        - keybase
        - gimp
        - appcleaner
        - hatari
        - licecap
      tags: cask

  roles:

    - role: rbenv
      rbenv_rubies:
        - 2.5.1
      rbenv_global: 2.5.1
